name: Akaunting CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update and Upgrade System
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install PHP and Extensions
        run: |
          sudo apt install -y lsb-release ca-certificates apt-transport-https software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt install -y php8.2
          sudo apt install -y php8.2-{bcmath,xml,fpm,mysql,zip,intl,ldap,gd,cli,bz2,curl,mbstring,pgsql,opcache,soap,cgi}

      - name: Install MariaDB Database server
        run: |
          sudo apt install -y mariadb-server mariadb-client
          sudo mysql -u root -p -e "CREATE DATABASE akaunting;"
          sudo mysql -u root -p -e "GRANT ALL PRIVILEGES ON akaunting.* TO 'akaunting'@'localhost' IDENTIFIED BY 'StrongPassword';"
          sudo mysql -u root -p -e "FLUSH PRIVILEGES;"

      - name: Clone Akaunting Repository
        run: |
          sudo apt install -y git
          sudo rm -rf /var/www/akaunting
          sudo git clone https://github.com/elbahiayoub/akaunting.git /var/www/akaunting

      - name: Install Nginx and Configure Akaunting
        run: |
          sudo apt remove -y apache2
          sudo apt install -y nginx
          sudo chown -R www-data:www-data /var/www/akaunting
          # Add and modify the Nginx configuration here
          sudo systemctl restart nginx php8.2-fpm.service
